### ISSUE TITLE
NameError: uninitialized constant Slim::Embedded::ERBEngine

### ISSUE THREAD

**Issue by rgaufman** [yury/coffee-views#6]
After a recent bundle update, I'm getting this:

```
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/coffee-views-0.2.0/lib/coffee_views/slim.rb:5:in `block in <main>'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/coffee-views-0.2.0/lib/coffee_views/slim.rb:6:in `<module:CoffeeViews>'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:42:in `load_missing_constant'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `rescue in load_missing_constant'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
/usr/local/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.1/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant': uninitialized constant Slim::Embedded::ERBEngine (NameError)
```

Any ideas?

**Comment by eyalfishler** [comment]
@rgaufman have you resolved this? thanks.

**Comment by rgaufman** [comment]
We stopped using coffeescript
